### ISSUE TITLE
Unable to install with StriderCD 1.6.0

### ISSUE THREAD

**Issue by mingfang** [Strider-CD/strider-github#30]
2015-01-17_22:23:03.54172 /strider/node_modules/strider-github/lib/webapp.js:71
2015-01-17_22:23:03.54183       clientSecret: config.appSecret
2015-01-17_22:23:03.54183       ^^^^^^^^^^^^
2015-01-17_22:23:03.54751 2015-01-17T22:23:03.547Z - info: failed to load plugin github Unexpected identifier SyntaxError: Unexpected identifier
2015-01-17_22:23:03.54751     at Module._compile (module.js:439:25)
2015-01-17_22:23:03.54752     at Object.Module._extensions..js (module.js:474:10)
2015-01-17_22:23:03.54752     at Module.load (module.js:356:32)
2015-01-17_22:23:03.54752     at Function.Module._load (module.js:312:12)
2015-01-17_22:23:03.54752     at Module.require (module.js:364:17)
2015-01-17_22:23:03.54753     at require (module.js:380:17)
2015-01-17_22:23:03.54753     at /strider/node_modules/strider-extension-loader/lib/index.js:323:29
2015-01-17_22:23:03.54753     at /strider/node_modules/strider-extension-loader/lib/index.js:354:11
2015-01-17_22:23:03.54753     at /strider/node_modules/strider-extension-loader/node_modules/async/lib/async.js:511:21
2015-01-17_22:23:03.54753     at /strider/node_modules/strider-extension-loader/node_modules/async/lib/async.js:227:13
2015-01-17_22:23:03.54797 2015-01-17T22:23:03.547Z - error: [SyntaxError: Unexpected identifier; error loading plugin github]
2015-01-17_22:23:03.54822 2015-01-17T22:23:03.548Z - error: Failed to load plugins

**Comment by knownasilya** [comment]
This has been fixed, update your version of `strider-github` to 1.3.2 via the plugin manager. You might have to first remove `node_modules/strider-github`.. If you have issues, please reopen.
