### ISSUE TITLE
Failure When Adding Second Github Account

### ISSUE THREAD

**Issue by fny** [Strider-CD/strider-github#38]
I successfully setup a Strider account and attached a Github repo to it. When attempting this with a second Strider account, however, I received the following 500 error during the callback from Github:

```
Connect
500 TypeError: Cannot read property '0' of undefined
   at makeAccount (/app/node_modules/strider-github/lib/webapp.js:167:28)
   at Strategy.validateAuth [as _verify] (/app/node_modules/strider-github/lib/webapp.js:152:26)
   at /app/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:188:22
   at /app/node_modules/strider-github/node_modules/passport-github/lib/strategy.js:109:5
   at passBackControl (/app/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:125:9)
   at IncomingMessage.<anonymous> (/app/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:142:7)
   at IncomingMessage.emit (events.js:129:20)
   at _stream_readable.js:908:16
   at process._tickCallback (node.js:355:11)
```

**Comment by fny** [comment]
Figured it out. That user did not have their email set as public. Is there any reason why that's a necessity?

**Comment by knownasilya** [comment]
As far as I know it's there to authenticate.

Also it seems like you are using an older version of strider-github, make sure to update your plugins via Admin > Plugins on the latest version of Strider
